apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --providers.kubernetescrd
            - --log.level=DEBUG
            - --certificatesresolvers.default.acme.dnsChallenge.provider=inwx
            - --certificatesresolvers.default.acme.dnsChallenge.resolvers=8.8.8.8:53,1.1.1.1:53
            - --certificatesresolvers.default.acme.email=codedrift.developer+lek8s@gmail.com
            - --certificatesresolvers.default.acme.storage=acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080
          env:
            - name: INWX_USERNAME
              value: ""
            - name: INWX_PASSWORD
              value: ""
            - name: INWX_PROPAGATION_TIMEOUT
              value: "10000"